# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_lastname <- function(strings, threads, model_path) {
    .Call(`_rethnicity_predict_lastname`, strings, threads, model_path)
}

predict_fullname <- function(strings_fn, strings_ln, threads, model_path) {
    .Call(`_rethnicity_predict_fullname`, strings_fn, strings_ln, threads, model_path)
}

