# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

char_split <- function(s) {
    .Call(`_rethnicity_char_split`, s)
}

test_cpp <- function(model_path) {
    .Call(`_rethnicity_test_cpp`, model_path)
}

test_lastname <- function(model_path) {
    .Call(`_rethnicity_test_lastname`, model_path)
}

