# using template and modified from https://github.com/r-devel/recheck

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Reverse dependency check

jobs:
  revdep_check:
    name: Reverse check ${{ inputs.which }} dependents
    uses: r-devel/recheck/.github/workflows/recheck.yml@v1
    with:
      which: most  # strong or most
      subdirectory: '' #if your package is in a git subdir
